version: '3'

services:
  bluekey-insight-frontend-prod:
    container_name: bluekey-insight-frontend-prod
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        BASE_URL: ${BASE_URL}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}

    restart: always
    ports:
      - 3001:3000