version: '3'

services:
  bluekey-insight-frontend:
    container_name: bluekey-insight-frontend
    build:
      context: .
      dockerfile: dev.Dockerfile

    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
